name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20  # 推荐使用 Node.js 20 或 18 LTS

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Verify output directory
        run: |
          ls -la ./out  # Next.js 直接輸出到根目錄的 out 資料夾
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out  # 已經正確設定為 ./out
          keep_files: false
          force_orphan: true  # 確保完全清理舊文件
